### ISSUE TITLE
recommendation: remove hurdles

### ISSUE THREAD

**Issue by mattmeye** [Vmlweb/MEAN-AngularJS-2#15]
im not able to run the demo out of the box, because:

- certs/ssl: (a) comment ssl out (b) add example certs (c) add gulp routine to create self signed certs
- mongodb: im not able to connect mongo
on a fresh mashine i have to call "docker pull mongo" manually one time (gulp: "no local image mongo"), why you don't connect app and db-container with link? host-ip is not longer needed - change config to optional use of an external mongodb
- ports: pls do not use ports 80,443 by default - for development it is absolute ok to use ports between 49152-65535 to prevent port collision

if i able to connect mongodb, i will complete this list!

PS: Nice Work! First Mean-Stack with Angular4 that i have seen.

**Comment by mattmeye** [comment]
Ok, i find your cert-setup-routine:

i have not installed yet open ssl win. for cross plattform i recommend you to use docker to create certs e.g. https://dzone.com/articles/using-docker-to-generate-ssl-certificates

**Comment by mattmeye** [comment]
thank you very much!

**Comment by VictorLeach96** [comment]
Thanks for the recommendations, let me know if you have any more.
